
server:
  port: 8090
  servlet:
    contextPath: /auth

signing:
  key: "345345fsdgsf5345"

---

# ================ DEFAULT ================

spring:
  profiles: default
  application:
    name: oauth2

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

---

# ================ DEV ================

 spring:
   profiles: dev
   application:
     name: oauth2

 eureka:
   instance:
     hostname: dev.avocadostudio.xyz
   client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:8761/eureka/