
server:
  port: 8090

logging:
  level:
    com.netflix: WARN
    org.springframework.web: DEBUG
    com.mo: DEBUG

signing:
  key: "345345fsdgsf5345"

env:
  host:
    local: localhost
    dev: dev.avocadostudio.xyz
  db:
    local:
      port: 3306
      schema: GUARD
    dev:
      port: 3306
      schema: GUARD

---

# ================ DEFAULT ================

spring:
  profiles: default
  application:
    name: auth

eureka:
  instance:
    hostname: ${env.host.local}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

---

# ================ DEV ================

 spring:
   profiles: dev
   application:
     name: auth

 eureka:
   instance:
     hostname: ${env.host.dev}
   client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:8761/eureka/